import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import {
  RefreshCw,
  Users,
  PhoneCall,
  CalendarCheck2,
  Trophy,
  Loader2,
  Download,
  Mail,
  Sparkles,
  X,
} from "lucide-react";
import { reportsApi, API_BASE_URL, type WeeklyReport } from "@/lib/api";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/_app/reports")({
  head: () => ({ meta: [{ title: "Reports — Nyumba Zetu" }] }),
  component: ReportsPage,
});

function ReportsPage() {
  const q = useQuery({ queryKey: ["reports", "weekly"], queryFn: reportsApi.weekly });
  const narrativeQ = useQuery({
    queryKey: ["reports", "weekly", "narrative"],
    queryFn: reportsApi.narrative,
    enabled: !q.isLoading,
  });
  const [emailOpen, setEmailOpen] = useState(false);

  const r: WeeklyReport = q.data ?? {};
  const a = r.activity ?? {};
  const narrative =
    narrativeQ.data?.narrative ?? narrativeQ.data?.text ?? "";

  const cards = [
    { label: "New Leads", value: a.new_leads, icon: Users },
    { label: "Calls Made", value: a.calls_made, icon: PhoneCall },
    { label: "Demos Booked", value: a.demos_booked, icon: CalendarCheck2 },
    { label: "Won", value: a.won, icon: Trophy },
  ];

  return (
    <div className="p-6 lg:p-8 space-y-6 print-report">
      <div className="print-header">Nyumba Zetu — Weekly Report</div>

      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-semibold">Weekly Reports</h1>
          <p className="text-sm text-muted-foreground mt-1">
            Sales activity and scraping coverage across the pipeline.
          </p>
        </div>
        <div className="flex items-center gap-2 no-print">
          <Button
            variant="outline"
            size="sm"
            onClick={() => q.refetch()}
            disabled={q.isFetching}
          >
            {q.isFetching ? (
              <Loader2 className="h-4 w-4 mr-1.5 animate-spin" />
            ) : (
              <RefreshCw className="h-4 w-4 mr-1.5" />
            )}
            Refresh
          </Button>
          <Button variant="outline" size="sm" onClick={() => window.print()}>
            <Download className="h-4 w-4 mr-1.5" />
            Download Report
          </Button>
          <Button size="sm" onClick={() => setEmailOpen(true)}>
            <Mail className="h-4 w-4 mr-1.5" />
            Email Report
          </Button>
        </div>
      </div>

      {/* AI narrative */}
      <div className="rounded-xl border border-border bg-card p-5 shadow-sm relative">
        {narrativeQ.isLoading ? (
          <div className="space-y-2 animate-pulse">
            <div className="h-3 w-1/3 bg-muted rounded" />
            <div className="h-3 w-full bg-muted rounded" />
            <div className="h-3 w-11/12 bg-muted rounded" />
            <div className="h-3 w-3/4 bg-muted rounded" />
          </div>
        ) : narrative ? (
          <>
            <p className="text-sm leading-relaxed whitespace-pre-wrap pr-24">
              {narrative}
            </p>
            <div className="absolute bottom-2 right-3 inline-flex items-center gap-1 text-[11px] text-muted-foreground">
              <Sparkles className="h-3 w-3" /> Generated by AI
            </div>
          </>
        ) : (
          <div className="text-sm text-muted-foreground italic">
            No narrative available.
          </div>
        )}
      </div>

      {/* SECTION A */}
      <section className="space-y-4">
        <h2 className="text-lg font-semibold">Sales activity (this week)</h2>

        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {cards.map((k) => {
            const Icon = k.icon;
            return (
              <div key={k.label} className="rounded-xl border border-border bg-card p-4 shadow-sm">
                <div className="flex items-center justify-between">
                  <div className="text-xs text-muted-foreground">{k.label}</div>
                  <Icon className="h-4 w-4 text-muted-foreground" />
                </div>
                <div className="mt-2 text-2xl font-semibold tabular-nums">
                  {q.isLoading ? "…" : (k.value ?? 0)}
                </div>
              </div>
            );
          })}
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
          <div className="rounded-xl border border-border bg-card p-5 shadow-sm">
            <div className="text-sm font-semibold mb-3">Top Performer</div>
            {r.top_performer ? (
              <div>
                <div className="text-lg font-semibold">{r.top_performer.name}</div>
                <div className="mt-2 flex gap-6 text-sm">
                  <div>
                    <div className="text-xs text-muted-foreground">Calls</div>
                    <div className="tabular-nums font-medium">{r.top_performer.calls ?? 0}</div>
                  </div>
                  <div>
                    <div className="text-xs text-muted-foreground">Demos</div>
                    <div className="tabular-nums font-medium">{r.top_performer.demos ?? 0}</div>
                  </div>
                  <div>
                    <div className="text-xs text-muted-foreground">Won</div>
                    <div className="tabular-nums font-medium">{r.top_performer.won ?? 0}</div>
                  </div>
                </div>
              </div>
            ) : (
              <div className="text-sm text-muted-foreground italic">
                No activity recorded yet this week
              </div>
            )}
          </div>

          <div className="rounded-xl border border-border bg-muted/40 p-5">
            <div className="text-xs text-muted-foreground">Developers tracked</div>
            <div className="mt-1 text-2xl font-semibold tabular-nums">
              {r.developers_tracked ?? 0}
            </div>
            <div className="mt-2 text-xs text-muted-foreground">
              Company-wide leads, not area-specific
            </div>
          </div>
        </div>

        <div className="rounded-xl border border-border bg-card shadow-sm">
          <div className="px-5 py-4 border-b border-border">
            <h3 className="font-semibold">Follow-ups</h3>
            <p className="text-xs text-muted-foreground mt-0.5">
              Overdue, due today, and upcoming in the next 7 days
            </p>
          </div>
          {(r.follow_ups_due ?? []).length === 0 ? (
            <div className="p-6 text-sm text-muted-foreground italic">
              No follow-ups due — pipeline is clean
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead className="bg-muted/40 text-muted-foreground">
                  <tr className="text-left">
                    <th className="px-4 py-3 font-medium">Name</th>
                    <th className="px-4 py-3 font-medium">Area</th>
                    <th className="px-4 py-3 font-medium">Type</th>
                    <th className="px-4 py-3 font-medium">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border">
                  {(r.follow_ups_due ?? []).map((f, i) => {
                    const urgency =
                      f.urgency ??
                      (f.days_overdue > 0
                        ? "overdue"
                        : f.days_overdue === 0
                          ? "due_today"
                          : "upcoming");
                    let cls = "";
                    let label = "";
                    if (urgency === "overdue") {
                      cls = "bg-destructive/10 text-destructive border-destructive/20";
                      label = `${Math.max(1, f.days_overdue)}d overdue`;
                    } else if (urgency === "due_today") {
                      cls = "bg-warning/15 text-warning-foreground border-warning/30";
                      label = "Due today";
                    } else {
                      cls = "bg-info/10 text-info border-info/20";
                      label = f.follow_up_date
                        ? new Date(f.follow_up_date).toLocaleDateString()
                        : `In ${Math.abs(f.days_overdue)}d`;
                    }
                    return (
                      <tr key={f.id ?? i} className="hover:bg-muted/30">
                        <td className="px-4 py-3 font-medium">{f.name}</td>
                        <td className="px-4 py-3 text-muted-foreground">{f.area ?? "—"}</td>
                        <td className="px-4 py-3 text-muted-foreground">{f.lead_type ?? "—"}</td>
                        <td className="px-4 py-3">
                          <span className={`inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-medium ${cls}`}>
                            {label}
                          </span>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </section>

      {/* SECTION B — Scraping */}
      <section className="space-y-4">
        <div>
          <h2 className="text-lg font-semibold">Scraped this week</h2>
          <p className="text-sm text-muted-foreground">
            Scraper runs recorded over the past 7 days
          </p>
        </div>

        <div className="rounded-xl border border-border bg-card shadow-sm overflow-x-auto">
          {(r.scraped_this_week ?? []).length === 0 ? (
            <div className="p-6 text-sm text-muted-foreground italic">
              No scraper runs recorded this week
            </div>
          ) : (
            <table className="w-full text-sm">
              <thead className="bg-muted/40 text-muted-foreground">
                <tr className="text-left">
                  <th className="px-4 py-3 font-medium">Area</th>
                  <th className="px-4 py-3 font-medium">Type</th>
                  <th className="px-4 py-3 font-medium">Records Found</th>
                  <th className="px-4 py-3 font-medium">Imported</th>
                  <th className="px-4 py-3 font-medium">Duplicates</th>
                  <th className="px-4 py-3 font-medium">Rejected</th>
                  <th className="px-4 py-3 font-medium">Last Run</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {(r.scraped_this_week ?? []).map((s, i) => {
                  const imp = s.imported ?? 0;
                  const rej = s.rejected ?? 0;
                  return (
                    <tr key={`${s.area}-${i}`} className="hover:bg-muted/30">
                      <td className="px-4 py-3 font-medium">{s.area}</td>
                      <td className="px-4 py-3 text-muted-foreground">{s.type ?? "—"}</td>
                      <td className="px-4 py-3 tabular-nums">{s.records_found ?? 0}</td>
                      <td className={`px-4 py-3 tabular-nums font-medium ${imp > 0 ? "text-success" : "text-muted-foreground"}`}>
                        {imp}
                      </td>
                      <td className="px-4 py-3 tabular-nums text-muted-foreground">{s.duplicates ?? 0}</td>
                      <td className={`px-4 py-3 tabular-nums font-medium ${rej > 0 ? "text-destructive" : "text-muted-foreground"}`}>
                        {rej}
                      </td>
                      <td className="px-4 py-3 text-muted-foreground">
                        {s.last_run ? new Date(s.last_run).toLocaleString() : "—"}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          )}
        </div>

        <div>
          <h3 className="font-semibold">
            Untapped this week ({(r.untapped_this_week ?? []).length})
          </h3>
          <div className="mt-2 flex flex-wrap gap-2">
            {(r.untapped_this_week ?? []).map((ar) => (
              <span
                key={ar}
                className="inline-flex items-center rounded-full bg-muted text-muted-foreground px-2.5 py-1 text-xs font-medium"
              >
                {ar}
              </span>
            ))}
            {(r.untapped_this_week ?? []).length === 0 && (
              <span className="text-sm text-muted-foreground italic">
                All tracked areas were scraped this week.
              </span>
            )}
          </div>
          <p className="mt-2 text-xs text-muted-foreground">
            Run the scraper on these areas to find new leads
          </p>
        </div>
      </section>

      {emailOpen && (
        <EmailReportDialog
          narrative={narrative}
          onClose={() => setEmailOpen(false)}
        />
      )}
    </div>
  );
}

function CoverageCell({ v, bold }: { v: number; bold?: boolean }) {
  const cls =
    v > 0
      ? "bg-success/15 text-success"
      : "bg-muted text-muted-foreground";
  return (
    <td className="px-4 py-3">
      <span
        className={`inline-flex min-w-[2rem] justify-center rounded-md px-2 py-0.5 text-xs tabular-nums ${cls} ${bold ? "font-semibold" : "font-medium"}`}
      >
        {v}
      </span>
    </td>
  );
}

function EmailReportDialog({
  narrative,
  onClose,
}: {
  narrative: string;
  onClose: () => void;
}) {
  const [to, setTo] = useState("");
  const dashUrl =
    typeof window !== "undefined" ? window.location.origin : API_BASE_URL;

  const send = () => {
    const dateStr = new Date().toLocaleDateString();
    const subject = `Nyumba Zetu Weekly Report — ${dateStr}`;
    const body = `${narrative || "Weekly report attached."}\n\nView full dashboard: ${dashUrl}`;
    const href = `mailto:${encodeURIComponent(to)}?subject=${encodeURIComponent(
      subject,
    )}&body=${encodeURIComponent(body)}`;
    window.location.href = href;
    onClose();
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 no-print"
      onClick={onClose}
    >
      <div
        className="bg-background rounded-xl border border-border shadow-xl w-full max-w-md p-5"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-start justify-between mb-3">
          <h3 className="font-semibold text-lg">Email Weekly Report</h3>
          <button
            onClick={onClose}
            className="rounded-md p-1.5 hover:bg-muted text-muted-foreground"
            aria-label="Close"
          >
            <X className="h-4 w-4" />
          </button>
        </div>
        <label className="text-sm font-medium">To</label>
        <input
          type="email"
          value={to}
          onChange={(e) => setTo(e.target.value)}
          placeholder="teammate@company.com"
          className="mt-1 w-full h-9 rounded-lg border border-input bg-background px-3 text-sm"
        />
        <div className="mt-4">
          <div className="text-sm font-medium mb-1">Preview</div>
          <div className="rounded-lg border border-border bg-muted/30 p-3 text-sm max-h-48 overflow-y-auto whitespace-pre-wrap">
            {narrative || (
              <span className="italic text-muted-foreground">
                No narrative available yet.
              </span>
            )}
          </div>
        </div>
        <div className="mt-5 flex justify-end gap-2">
          <Button variant="outline" size="sm" onClick={onClose}>
            Cancel
          </Button>
          <Button size="sm" onClick={send} disabled={!to.trim()}>
            <Mail className="h-4 w-4 mr-1.5" />
            Send
          </Button>
        </div>
      </div>
    </div>
  );
}
