/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppScrapeRouteImport } from './routes/_app.scrape'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppLandlordsRouteImport } from './routes/_app.landlords'
import { Route as AppDevelopersRouteImport } from './routes/_app.developers'
import { Route as AppApartmentsRouteImport } from './routes/_app.apartments'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAgenciesRouteImport } from './routes/_app.agencies'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScrapeRoute = AppScrapeRouteImport.update({
  id: '/scrape',
  path: '/scrape',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppLandlordsRoute = AppLandlordsRouteImport.update({
  id: '/landlords',
  path: '/landlords',
  getParentRoute: () => AppRoute,
} as any)
const AppDevelopersRoute = AppDevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => AppRoute,
} as any)
const AppApartmentsRoute = AppApartmentsRouteImport.update({
  id: '/apartments',
  path: '/apartments',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAgenciesRoute = AppAgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/signin': typeof SigninRoute
  '/agencies': typeof AppAgenciesRoute
  '/analytics': typeof AppAnalyticsRoute
  '/apartments': typeof AppApartmentsRoute
  '/developers': typeof AppDevelopersRoute
  '/landlords': typeof AppLandlordsRoute
  '/leads': typeof AppLeadsRoute
  '/reports': typeof AppReportsRoute
  '/scrape': typeof AppScrapeRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesByTo {
  '/change-password': typeof ChangePasswordRoute
  '/signin': typeof SigninRoute
  '/agencies': typeof AppAgenciesRoute
  '/analytics': typeof AppAnalyticsRoute
  '/apartments': typeof AppApartmentsRoute
  '/developers': typeof AppDevelopersRoute
  '/landlords': typeof AppLandlordsRoute
  '/leads': typeof AppLeadsRoute
  '/reports': typeof AppReportsRoute
  '/scrape': typeof AppScrapeRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/signin': typeof SigninRoute
  '/_app/agencies': typeof AppAgenciesRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/apartments': typeof AppApartmentsRoute
  '/_app/developers': typeof AppDevelopersRoute
  '/_app/landlords': typeof AppLandlordsRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/scrape': typeof AppScrapeRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/signin'
    | '/agencies'
    | '/analytics'
    | '/apartments'
    | '/developers'
    | '/landlords'
    | '/leads'
    | '/reports'
    | '/scrape'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/change-password'
    | '/signin'
    | '/agencies'
    | '/analytics'
    | '/apartments'
    | '/developers'
    | '/landlords'
    | '/leads'
    | '/reports'
    | '/scrape'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/change-password'
    | '/signin'
    | '/_app/agencies'
    | '/_app/analytics'
    | '/_app/apartments'
    | '/_app/developers'
    | '/_app/landlords'
    | '/_app/leads'
    | '/_app/reports'
    | '/_app/scrape'
    | '/_app/settings'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scrape': {
      id: '/_app/scrape'
      path: '/scrape'
      fullPath: '/scrape'
      preLoaderRoute: typeof AppScrapeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/landlords': {
      id: '/_app/landlords'
      path: '/landlords'
      fullPath: '/landlords'
      preLoaderRoute: typeof AppLandlordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developers': {
      id: '/_app/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof AppDevelopersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apartments': {
      id: '/_app/apartments'
      path: '/apartments'
      fullPath: '/apartments'
      preLoaderRoute: typeof AppApartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agencies': {
      id: '/_app/agencies'
      path: '/agencies'
      fullPath: '/agencies'
      preLoaderRoute: typeof AppAgenciesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgenciesRoute: typeof AppAgenciesRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApartmentsRoute: typeof AppApartmentsRoute
  AppDevelopersRoute: typeof AppDevelopersRoute
  AppLandlordsRoute: typeof AppLandlordsRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppScrapeRoute: typeof AppScrapeRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgenciesRoute: AppAgenciesRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApartmentsRoute: AppApartmentsRoute,
  AppDevelopersRoute: AppDevelopersRoute,
  AppLandlordsRoute: AppLandlordsRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppReportsRoute: AppReportsRoute,
  AppScrapeRoute: AppScrapeRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
